### ISSUE TITLE
Getting tree data doesnt work

### ISSUE THREAD

**Issue by ivanistheone** [fle-internal/sushibar#16]
Currently opening pre-existing channels don't show trees

![screen shot 2017-11-08 at 12 19 16 pm](https://user-images.githubusercontent.com/163966/32563435-424829ba-c47f-11e7-8a9a-efb10ec81bda.png)

expected: channel tree data to be populated after every run.

**Comment by jayoshih** [comment]
Ah sorry, endpoint wasn't on studio yet.  Should be now if you run the chef again

**Comment by ivanistheone** [comment]
Open Osmosis still fails (presumably while trying to compute stats):

```
ERROR 2017-11-22 17:09:09,424 exception 22 140672750937856 Internal Server Error: /runs/7f21892b-f59a-4f7a-a52c-ffb1e9e10d0e/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/sushibar/dashboard/views.py", line 293, in get
    return super(RunView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 155, in get
    context = self.get_context_data(**kwargs)
  File "/app/sushibar/dashboard/views.py", line 383, in get_context_data
    modify_data_recursively(tree_data)
  File "/app/sushibar/dashboard/views.py", line 282, in modify_data_recursively
    modify_data_recursively(root["children"])
  File "/app/sushibar/dashboard/views.py", line 282, in modify_data_recursively
    modify_data_recursively(root["children"])
  File "/app/sushibar/dashboard/views.py", line 282, in modify_data_recursively
    modify_data_recursively(root["children"])
  File "/app/sushibar/dashboard/views.py", line 280, in modify_data_recursively
    root["file_size"] = sizeof_fmt(root["file_size"])
  File "/app/sushibar/dashboard/views.py", line 230, in sizeof_fmt
    if abs(num) < 1024.0:
TypeError: bad operand type for abs(): 'NoneType'
```

**Comment by ivanistheone** [comment]
All channel data seems to load fine now.
